#!/bin/bash 

function getcontman {
	local contman=""

	if command -v podman > /dev/null; then
		contman="podman"
	elif command -v docker > /dev/null; then
		contman="docker"
	else
		echo "You need to install podman or docker."
	fi

	echo "$contman"
}

function getbuildargs {
	local buildargs=""

	if command -v podman > /dev/null; then
		buildargs="--pull-always --squash-all"
	elif command -v docker > /dev/null; then
		buildargs="-f ./Containerfile"
	else
		echo "You need to install podman or docker."
	fi

	echo "$buildargs"
}

function buildimage {
	local contman="$(getcontman)"
	local buildargs="$(getbuildargs)"

	cd $1
	local image=$(dirname "$1")
	local label=$(basename "$1")
	"$contman" build . $buildargs --tag "$image:$label"
	cd -
}

function saveimage {
	local contman="$(getcontman)"

	cd $1
	local image=$(dirname "$1")
	local label=$(basename "$1")
	echo "$contman" save "localhost/$image:$label" | gzip > "$image-$label.tar.gz"
	cd -
}
