#!/bin/bash 
# shellcheck disable=SC2155

function getcontman {
	local contman="$DBX_CONTAINER_MANAGER"

	if test -z "$contman"; then
		if command -v podman > /dev/null; then
			contman="podman"
		elif command -v docker > /dev/null; then
			contman="docker"
		else
			echo "You need to install podman or docker."
		fi
	fi

	echo "$contman"
}

function getbuildargs {
	local contman=$(getcontman)
	local buildargs=""

	if test "$contman" = "podman"; then
		buildargs="--pull-always --squash-all"
	elif test "$contman" = "docker"; then
		buildargs="-f ./Containerfile --force-rm --pull --squash --no-cache"
	else
		echo "You need to install podman or docker."
	fi

	echo "$buildargs"
}

function gettag {
	# args example: ubuntu-distrobox/20.04 :
	local prefix="./"
	local image=$(dirname "$1")
	local label=$(basename "$1")
	local separator=$2

	image=${image#"$prefix"}

	echo "$image$separator$label"
}

function buildimage {
	local contman="$(getcontman)"
	local buildargs="$(getbuildargs)"

	cd "$1" || return 1
	local tag=$(gettag "$1" ":")
	# shellcheck disable=SC2086
	"$contman" build . $buildargs --tag "$tag"
	cd - || return 1
}

function saveimage {
	local contman="$(getcontman)"

	cd "$1" || return 1
	local tag=$(gettag "$1" ":")
	local filename=$(gettag "$1" "-")
	"$contman" save "$tag" | gzip > "$filename.tar.gz"
	cd - || return 1
}
